# Generated by Django 5.1.6 on 2025-02-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_skill_alter_project_image_alter_project_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
