# Generated by Django 5.1.6 on 2025-02-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_skill_alter_project_image_alter_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
